// #region 退款申请状态
// Types
export const REFUND_APPLICATION_STATUS = {
  /** 待审核 */
  PENDING: 0,
  /** 审核通过 */
  APPROVED: 1,
  /** 退款处理中（部分完成） */
  PROCESSING_PARTIAL: 2,
  /** 全部退款完成 */
  COMPLETED_ALL: 3,
  /** 部分退款完成（有成功有失败） */
  COMPLETED_PARTIAL: 4,
  /** 审核拒绝 */
  REJECTED: 5,
  /** 用户取消 */
  CANCELLED: 6,
} as const

export type TRefundApplicationStatus
  = (typeof REFUND_APPLICATION_STATUS)[keyof typeof REFUND_APPLICATION_STATUS]

// I18N
export const REFUND_APPLICATION_STATUS_I18N: Record<TRefundApplicationStatus, string> = {
  [REFUND_APPLICATION_STATUS.PENDING]: '待审核',
  [REFUND_APPLICATION_STATUS.APPROVED]: '审核通过',
  [REFUND_APPLICATION_STATUS.PROCESSING_PARTIAL]: '退款处理中',
  [REFUND_APPLICATION_STATUS.COMPLETED_ALL]: '全部退款完成',
  [REFUND_APPLICATION_STATUS.COMPLETED_PARTIAL]: '部分退款完成',
  [REFUND_APPLICATION_STATUS.REJECTED]: '审核拒绝',
  [REFUND_APPLICATION_STATUS.CANCELLED]: '用户取消',
}

// Options
export const REFUND_APPLICATION_STATUS_OPTIONS = [
  {
    label: REFUND_APPLICATION_STATUS_I18N[REFUND_APPLICATION_STATUS.PENDING],
    value: REFUND_APPLICATION_STATUS.PENDING,
  },
  {
    label: REFUND_APPLICATION_STATUS_I18N[REFUND_APPLICATION_STATUS.APPROVED],
    value: REFUND_APPLICATION_STATUS.APPROVED,
  },
  {
    label: REFUND_APPLICATION_STATUS_I18N[REFUND_APPLICATION_STATUS.PROCESSING_PARTIAL],
    value: REFUND_APPLICATION_STATUS.PROCESSING_PARTIAL,
  },
  {
    label: REFUND_APPLICATION_STATUS_I18N[REFUND_APPLICATION_STATUS.COMPLETED_ALL],
    value: REFUND_APPLICATION_STATUS.COMPLETED_ALL,
  },
  {
    label: REFUND_APPLICATION_STATUS_I18N[REFUND_APPLICATION_STATUS.COMPLETED_PARTIAL],
    value: REFUND_APPLICATION_STATUS.COMPLETED_PARTIAL,
  },
  {
    label: REFUND_APPLICATION_STATUS_I18N[REFUND_APPLICATION_STATUS.REJECTED],
    value: REFUND_APPLICATION_STATUS.REJECTED,
  },
  {
    label: REFUND_APPLICATION_STATUS_I18N[REFUND_APPLICATION_STATUS.CANCELLED],
    value: REFUND_APPLICATION_STATUS.CANCELLED,
  },
]
// #endregion
