import type { TI18NMap, TOptions } from '@/types'

// Types
export const AMOUNT_TYPE = {
  RECHARGE: 'RECHARGE',
  CONSUMPTION: 'CONSUMPTION',
  CARD_RECHARGE: 'CARD_RECHARGE',
  REFUND: 'REFUND',
  FREEZE: 'FREEZE',
  UNFREEZE: 'UNFREEZE',
  ADJUST: 'ADJUST',
  PACKAGE_PURCHASE: 'PACKAGE_PURCHASE',
} as const

export type TAmountType = (typeof AMOUNT_TYPE)[keyof typeof AMOUNT_TYPE]

// I18N
export const AMOUNT_TYPE_I18N: TI18NMap<TAmountType> = {
  [AMOUNT_TYPE.RECHARGE]: '充值',
  [AMOUNT_TYPE.CONSUMPTION]: '消费',
  [AMOUNT_TYPE.CARD_RECHARGE]: '圈存',
  [AMOUNT_TYPE.REFUND]: '退款',
  [AMOUNT_TYPE.FREEZE]: '冻结',
  [AMOUNT_TYPE.UNFREEZE]: '解冻',
  [AMOUNT_TYPE.ADJUST]: '调整',
  [AMOUNT_TYPE.PACKAGE_PURCHASE]: '套餐购买',
}

// Options
export const AMOUNT_TYPE_OPTIONS: TOptions<TAmountType> = [
  { label: AMOUNT_TYPE_I18N[AMOUNT_TYPE.RECHARGE], value: AMOUNT_TYPE.RECHARGE },
  { label: AMOUNT_TYPE_I18N[AMOUNT_TYPE.CONSUMPTION], value: AMOUNT_TYPE.CONSUMPTION },
  { label: AMOUNT_TYPE_I18N[AMOUNT_TYPE.CARD_RECHARGE], value: AMOUNT_TYPE.CARD_RECHARGE },
  { label: AMOUNT_TYPE_I18N[AMOUNT_TYPE.REFUND], value: AMOUNT_TYPE.REFUND },
  { label: AMOUNT_TYPE_I18N[AMOUNT_TYPE.FREEZE], value: AMOUNT_TYPE.FREEZE },
  { label: AMOUNT_TYPE_I18N[AMOUNT_TYPE.UNFREEZE], value: AMOUNT_TYPE.UNFREEZE },
  { label: AMOUNT_TYPE_I18N[AMOUNT_TYPE.ADJUST], value: AMOUNT_TYPE.ADJUST },
  { label: AMOUNT_TYPE_I18N[AMOUNT_TYPE.PACKAGE_PURCHASE], value: AMOUNT_TYPE.PACKAGE_PURCHASE },
]

// 获取交易类型的图标
export const AMOUNT_TYPE_ICON_MAP: Record<TAmountType, string> = {
  [AMOUNT_TYPE.RECHARGE]: 'add-circle-line',
  [AMOUNT_TYPE.CONSUMPTION]: 'subtract-line',
  [AMOUNT_TYPE.CARD_RECHARGE]: 'bank-card-line',
  [AMOUNT_TYPE.REFUND]: 'refund-2-line',
  [AMOUNT_TYPE.FREEZE]: 'lock-line',
  [AMOUNT_TYPE.UNFREEZE]: 'lock-unlock-line',
  [AMOUNT_TYPE.ADJUST]: 'settings-line',
  [AMOUNT_TYPE.PACKAGE_PURCHASE]: 'shopping-bag-line',
}

// 正向金额类型（显示为正数）
export const POSITIVE_AMOUNT_TYPES: TAmountType[] = [
  AMOUNT_TYPE.RECHARGE,
  AMOUNT_TYPE.REFUND,
  AMOUNT_TYPE.UNFREEZE,
]

export const BALANCE_BUSINESS_TYPE = {
  PAYMENT: 'PAYMENT',
  CONSUMPTION: 'CONSUMPTION',
  CARD_RECHARGE: 'CARD_RECHARGE',
  REFUND_APPLICATION: 'REFUND_APPLICATION',
  PACKAGE_PURCHASE: 'PACKAGE_PURCHASE',
  ADMIN_ADJUST: 'ADMIN_ADJUST',
} as const

export type TBalanceBusinessType = (typeof BALANCE_BUSINESS_TYPE)[keyof typeof BALANCE_BUSINESS_TYPE]

export const BALANCE_BUSINESS_TYPE_I18N: TI18NMap<TBalanceBusinessType> = {
  [BALANCE_BUSINESS_TYPE.PAYMENT]: '支付',
  [BALANCE_BUSINESS_TYPE.CONSUMPTION]: '消费',
  [BALANCE_BUSINESS_TYPE.CARD_RECHARGE]: '圈存',
  [BALANCE_BUSINESS_TYPE.REFUND_APPLICATION]: '退费申请',
  [BALANCE_BUSINESS_TYPE.PACKAGE_PURCHASE]: '套餐购买',
  [BALANCE_BUSINESS_TYPE.ADMIN_ADJUST]: '管理调整',
}

export const BALANCE_BUSINESS_TYPE_OPTIONS: TOptions<TBalanceBusinessType> = [
  { label: BALANCE_BUSINESS_TYPE_I18N[BALANCE_BUSINESS_TYPE.PAYMENT], value: BALANCE_BUSINESS_TYPE.PAYMENT },
  { label: BALANCE_BUSINESS_TYPE_I18N[BALANCE_BUSINESS_TYPE.CONSUMPTION], value: BALANCE_BUSINESS_TYPE.CONSUMPTION },
  { label: BALANCE_BUSINESS_TYPE_I18N[BALANCE_BUSINESS_TYPE.CARD_RECHARGE], value: BALANCE_BUSINESS_TYPE.CARD_RECHARGE },
  { label: BALANCE_BUSINESS_TYPE_I18N[BALANCE_BUSINESS_TYPE.REFUND_APPLICATION], value: BALANCE_BUSINESS_TYPE.REFUND_APPLICATION },
  { label: BALANCE_BUSINESS_TYPE_I18N[BALANCE_BUSINESS_TYPE.PACKAGE_PURCHASE], value: BALANCE_BUSINESS_TYPE.PACKAGE_PURCHASE },
  { label: BALANCE_BUSINESS_TYPE_I18N[BALANCE_BUSINESS_TYPE.ADMIN_ADJUST], value: BALANCE_BUSINESS_TYPE.ADMIN_ADJUST },
]
