// Types
export const SUBSCRIPTION_STATUS = {
  UNSUBSCRIBED: 0,
  SUBSCRIBED: 1,
} as const

export type TSubscriptionStatus = (typeof SUBSCRIPTION_STATUS)[keyof typeof SUBSCRIPTION_STATUS]

// I18N
export const SUBSCRIPTION_STATUS_I18N: Record<TSubscriptionStatus, string> = {
  [SUBSCRIPTION_STATUS.UNSUBSCRIBED]: '未订阅',
  [SUBSCRIPTION_STATUS.SUBSCRIBED]: '已订阅',
}

// Options
export const SUBSCRIPTION_STATUS_OPTIONS = [
  { label: SUBSCRIPTION_STATUS_I18N[SUBSCRIPTION_STATUS.UNSUBSCRIBED], value: SUBSCRIPTION_STATUS.UNSUBSCRIBED },
  { label: SUBSCRIPTION_STATUS_I18N[SUBSCRIPTION_STATUS.SUBSCRIBED], value: SUBSCRIPTION_STATUS.SUBSCRIBED },
]
