/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomPopup: typeof import('./../components/popup/bottom-popup/index.vue')['default']
    Button: typeof import('./../components/common/button/index.vue')['default']
    Cell: typeof import('./../components/form/cell/index.vue')['default']
    DatetimePickerPopup: typeof import('./../components/popup/datetime-picker-popup/index.vue')['default']
    DefaultBg: typeof import('./../components/common/default-bg/index.vue')['default']
    DetailBlock: typeof import('./../components/common/detail-block/index.vue')['default']
    FabActions: typeof import('./../components/common/fab-actions/index.vue')['default']
    FilterGroup: typeof import('./../components/common/filter-group/index.vue')['default']
    FilterSelector: typeof import('./../components/common/filter-selector/index.vue')['default']
    FunctionList: typeof import('./../components/common/function-list/index.vue')['default']
    GradientHeader: typeof import('./../components/common/gradient-header/index.vue')['default']
    Icon: typeof import('./../components/icon/index.vue')['default']
    Index: typeof import('./../components/form/index/index.vue')['default']
    InputNumber: typeof import('./../components/form/input-number/index.vue')['default']
    Loading: typeof import('./../components/common/loading/index.vue')['default']
    Login: typeof import('./../components/popup/login/index.vue')['default']
    Navigation: typeof import('./../components/common/navigation/index.vue')['default']
    Notice: typeof import('./../components/common/notice/index.vue')['default']
    Page: typeof import('./../components/common/page/index.vue')['default']
    Picker: typeof import('./../components/form/picker/index.vue')['default']
    Radio: typeof import('./../components/form/radio/index.vue')['default']
    RefreshList: typeof import('./../components/common/refresh-list/index.vue')['default']
    RoleAvatar: typeof import('./../components/common/role-avatar/index.vue')['default']
    SelectorPopup: typeof import('./../components/popup/selector-popup/index.vue')['default']
    Tab: typeof import('./../components/common/tab/index.vue')['default']
    WhiteCard: typeof import('./../components/common/white-card/index.vue')['default']
  }
}
