/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/voip/test/index" |
       "/pages/launch/index" |
       "/pages/welcome/index" |
       "/pages/parent/home/index" |
       "/pages/parent/overview/index" |
       "/pages-sub/chat/index" |
       "/pages-sub/balance/history/index" |
       "/pages-sub/balance/home/index" |
       "/pages-sub/balance/recharge/index" |
       "/pages-sub/balance/result/index" |
       "/pages-sub/common/follow/index" |
       "/pages-sub/common/icon/index" |
       "/pages-sub/common/role-switch/index" |
       "/pages-sub/common/signature/index" |
       "/pages-sub/common/webview/index" |
       "/pages-sub/device/subscribe/index" |
       "/pages-sub/family/edit/index" |
       "/pages-sub/family/manage/index" |
       "/pages-sub/history/consumption/index" |
       "/pages-sub/history/fund/index" |
       "/pages-sub/package/detail/index" |
       "/pages-sub/package/list/index" |
       "/pages-sub/profile/edit/index" |
       "/pages-sub/service/privacy/index" |
       "/pages-sub/service/protocol/index" |
       "/pages-sub/service/purchase/index" |
       "/pages-sub/balance/refund/apply/index" |
       "/pages-sub/balance/refund/history/index" |
       "/pages-sub/balance/refund/result/index" |
       "/pages-sub/package/history/home/index" |
       "/pages-sub/package/history/result/index" |
       "/pages-sub/package/refund/history/index" |
       "/pages-sub/package/refund/result/index" |
       "/pages-sub/parent/student/bind/index" |
       "/pages-sub/parent/student/detail/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
