/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/launch/index" |
       "/pages/parent/index" |
       "/pages/welcome/index" |
       "/pages-sub/chat/index" |
       "/pages-sub/demo/datetime-picker-popup" |
       "/pages-sub/demo/icon" |
       "/pages-sub/demo/navigate-to-miniprogram" |
       "/pages-sub/demo/refresh-list" |
       "/pages-sub/balance/history/index" |
       "/pages-sub/balance/home/index" |
       "/pages-sub/balance/recharge/index" |
       "/pages-sub/balance/result/index" |
       "/pages-sub/common/follow/index" |
       "/pages-sub/common/role-switch/index" |
       "/pages-sub/common/signature/index" |
       "/pages-sub/consumption/history/index" |
       "/pages-sub/device/subscribe/index" |
       "/pages-sub/face/camera/index" |
       "/pages-sub/face/collection/index" |
       "/pages-sub/face/consent/index" |
       "/pages-sub/family/edit/index" |
       "/pages-sub/family/manage/index" |
       "/pages-sub/fund/balance/index" |
       "/pages-sub/fund/history/index" |
       "/pages-sub/package/detail/index" |
       "/pages-sub/package/history/index" |
       "/pages-sub/package/list/index" |
       "/pages-sub/profile/edit/index" |
       "/pages-sub/refund/apply/index" |
       "/pages-sub/refund/history/index" |
       "/pages-sub/refund/result/index" |
       "/pages-sub/service/privacy/index" |
       "/pages-sub/service/protocol/index" |
       "/pages-sub/service/purchase/index" |
       "/pages-sub/package/refund/history/index" |
       "/pages-sub/parent/student/bind/index" |
       "/pages-sub/parent/student/detail/index";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
