// Types
export const GIFT_SOURCE = {
  ADMIN_GIFT: 'ADMIN_GIFT',
  PROMOTION: 'PROMOTION',
  COMPENSATION: 'COMPENSATION',
  REWARD: 'REWARD',
} as const

export type TGiftSource = (typeof GIFT_SOURCE)[keyof typeof GIFT_SOURCE]

// I18N
export const GIFT_SOURCE_I18N = {
  [GIFT_SOURCE.ADMIN_GIFT]: '管理员赠送',
  [GIFT_SOURCE.PROMOTION]: '活动赠送',
  [GIFT_SOURCE.COMPENSATION]: '补偿赠送',
  [GIFT_SOURCE.REWARD]: '奖励赠送',
}

// Options
export const GIFT_SOURCE_OPTIONS = [
  { label: GIFT_SOURCE_I18N[GIFT_SOURCE.ADMIN_GIFT], value: GIFT_SOURCE.ADMIN_GIFT },
  { label: GIFT_SOURCE_I18N[GIFT_SOURCE.PROMOTION], value: GIFT_SOURCE.PROMOTION },
  { label: GIFT_SOURCE_I18N[GIFT_SOURCE.COMPENSATION], value: GIFT_SOURCE.COMPENSATION },
  { label: GIFT_SOURCE_I18N[GIFT_SOURCE.REWARD], value: GIFT_SOURCE.REWARD },
]
