// 亲情号称谓类型
export const RELATION_TYPE = {
  // 爸爸
  FATHER: '1',
  // 妈妈
  MOTHER: '2',
  // 爷爷
  GRANDFATHER: '3',
  // 奶奶
  GRANDMOTHER: '4',
  // 外公
  MATERNAL_GRANDFATHER: '5',
  // 外婆
  MATERNAL_GRANDMOTHER: '6',
  // 姐姐
  SISTER: '7',
  // 哥哥
  BROTHER: '8',
  // 其他
  OTHER: '9',
}
export const RELATION_TYPE_I18N = {
  [RELATION_TYPE.FATHER]: '爸爸',
  [RELATION_TYPE.MOTHER]: '妈妈',
  [RELATION_TYPE.GRANDFATHER]: '爷爷',
  [RELATION_TYPE.GRANDMOTHER]: '奶奶',
  [RELATION_TYPE.MATERNAL_GRANDFATHER]: '外公',
  [RELATION_TYPE.MATERNAL_GRANDMOTHER]: '外婆',
  [RELATION_TYPE.SISTER]: '姐姐',
  [RELATION_TYPE.BROTHER]: '哥哥',
  [RELATION_TYPE.OTHER]: '其他',
}
export const RELATION_TYPE_OPTIONS = [
  { value: RELATION_TYPE.FATHER, label: RELATION_TYPE_I18N[RELATION_TYPE.FATHER] },
  { value: RELATION_TYPE.MOTHER, label: RELATION_TYPE_I18N[RELATION_TYPE.MOTHER] },
  { value: RELATION_TYPE.GRANDFATHER, label: RELATION_TYPE_I18N[RELATION_TYPE.GRANDFATHER] },
  { value: RELATION_TYPE.GRANDMOTHER, label: RELATION_TYPE_I18N[RELATION_TYPE.GRANDMOTHER] },
  {
    value: RELATION_TYPE.MATERNAL_GRANDFATHER,
    label: RELATION_TYPE_I18N[RELATION_TYPE.MATERNAL_GRANDFATHER],
  },
  {
    value: RELATION_TYPE.MATERNAL_GRANDMOTHER,
    label: RELATION_TYPE_I18N[RELATION_TYPE.MATERNAL_GRANDMOTHER],
  },
  { value: RELATION_TYPE.SISTER, label: RELATION_TYPE_I18N[RELATION_TYPE.SISTER] },
  { value: RELATION_TYPE.BROTHER, label: RELATION_TYPE_I18N[RELATION_TYPE.BROTHER] },
  { value: RELATION_TYPE.OTHER, label: RELATION_TYPE_I18N[RELATION_TYPE.OTHER] },
]
