import { ALL } from '@/constant/modules/common'

// #region 学生套餐购买记录状态
// Types
export const STUDENT_PACKAGE_STATUS = {
  PENDING: 0, // 待支付
  WAITING_ACTIVE: 1, // 待激活（已支付，等待生效）
  ACTIVE: 2, // 有效/已激活
  EXPIRED: 3, // 已过期
  USED_UP: 4, // 已用完
  REFUNDED: 5, // 已退款
  CANCELLED: 6, // 已取消
  REFUND_PENDING: 7, // 申请退款中
} as const

export type TStudentPackageStatus
  = (typeof STUDENT_PACKAGE_STATUS)[keyof typeof STUDENT_PACKAGE_STATUS]

// I18N
export const STUDENT_PACKAGE_STATUS_I18N: Record<TStudentPackageStatus, string> = {
  [STUDENT_PACKAGE_STATUS.PENDING]: '待支付',
  [STUDENT_PACKAGE_STATUS.WAITING_ACTIVE]: '待激活',
  [STUDENT_PACKAGE_STATUS.ACTIVE]: '有效',
  [STUDENT_PACKAGE_STATUS.EXPIRED]: '已过期',
  [STUDENT_PACKAGE_STATUS.USED_UP]: '已用完',
  [STUDENT_PACKAGE_STATUS.REFUNDED]: '已退款',
  [STUDENT_PACKAGE_STATUS.CANCELLED]: '已取消',
  [STUDENT_PACKAGE_STATUS.REFUND_PENDING]: '申请退款中',
}

// Options
export const STUDENT_PACKAGE_STATUS_OPTIONS = [
  { value: ALL, label: '全部状态' },
  {
    label: STUDENT_PACKAGE_STATUS_I18N[STUDENT_PACKAGE_STATUS.PENDING],
    value: STUDENT_PACKAGE_STATUS.PENDING,
  },
  {
    label: STUDENT_PACKAGE_STATUS_I18N[STUDENT_PACKAGE_STATUS.WAITING_ACTIVE],
    value: STUDENT_PACKAGE_STATUS.WAITING_ACTIVE,
  },
  {
    label: STUDENT_PACKAGE_STATUS_I18N[STUDENT_PACKAGE_STATUS.ACTIVE],
    value: STUDENT_PACKAGE_STATUS.ACTIVE,
  },
  {
    label: STUDENT_PACKAGE_STATUS_I18N[STUDENT_PACKAGE_STATUS.EXPIRED],
    value: STUDENT_PACKAGE_STATUS.EXPIRED,
  },
  {
    label: STUDENT_PACKAGE_STATUS_I18N[STUDENT_PACKAGE_STATUS.USED_UP],
    value: STUDENT_PACKAGE_STATUS.USED_UP,
  },
  {
    label: STUDENT_PACKAGE_STATUS_I18N[STUDENT_PACKAGE_STATUS.REFUNDED],
    value: STUDENT_PACKAGE_STATUS.REFUNDED,
  },
  {
    label: STUDENT_PACKAGE_STATUS_I18N[STUDENT_PACKAGE_STATUS.CANCELLED],
    value: STUDENT_PACKAGE_STATUS.CANCELLED,
  },
  {
    label: STUDENT_PACKAGE_STATUS_I18N[STUDENT_PACKAGE_STATUS.REFUND_PENDING],
    value: STUDENT_PACKAGE_STATUS.REFUND_PENDING,
  },
]
// #endregion
